# -*- coding: utf-8 -*-
"""Quiz1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmiUXwlmC5iX0ubaOhrFbTpFnJVZV8KK

# **Quiz 1: Data Science Toolbox**

**Prepared by**: Dr. Hum Nath Bhandari

**Institution**: Roger Williams University

**Department**: Mathematics Department

**Student Name**: Ethan Haynes
   

### **Learning Outcome**

In this quiz you will be tested for your understanding of software installations and files management.

**Question 1**: 
- Download this Quiz and save into your local machine inside **Data Science** folder (you created this folder during my class). 
- Open the Quiz by using Jupyter notebook (Jupyter comes with anaconda installation). 
- Complete the first cell of this notebook by writing your name.
"""
print("Ethan Haynes");


"""**Question 2**: Write a **Hello world** python program  below."""

print("hello world");

"""**Question 3**: Create a python script file, called **my_first_file.py** using editor of spyder and write a python program to print: "Welcome to data science class!". Take a screenshot of the result from your program and insert the screenshot picture in the following cell. See [here](https://www.youtube.com/watch?v=Vw1EZh1My8s) for the guidelines of importing picture in notebook."""

![](my_first_file.jpg)

"""**Question 4**: After you are done upto **Question 3**, copy your quiz from your local machine to Google Drive and put into **Data Science** folder (I assume you created this folder based on our discussions in the class). Now open the file using Google Colab. Write a python program below to print: "Welcome back from Google Colab!". Provide a link of Colab url below."""

print("Welcome back from Google Colab!")

"""**Question 5**: After you are done with **Question 4**, save a copy of this quiz in Github inside **Data 
Science** folder which you had created based on our class discussion.
"""



"""**Question 6**: Provide a GitHub url of this quiz in the following cell."""



"""**Quiestion 7**: Provide the same GitHub url on bridges."""



